baseURL = 'https://unit.nazwa.pl/jedrzejewskisite/'
languageCode = 'pl-PL'
title = 'My blog'
theme = 'hugo-theme-m10c'
author = 'Mikołaj Jędrzejewski'
description = 'Mój opis'
avatar = '/avatar.ico'
menu_item_separator = '-'
favicon = '/favicon.ico'